services:
  - type: worker
    name: sgp-ticket-checker
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromEnv: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
        fromEnv: TELEGRAM_CHAT_ID
